name: Android 14 6.1
permissions:
  contents: write
  actions: write

on:
  workflow_call:
    inputs:
      use_zram:
        required: true
        type: boolean
        default: true
      use_kpm:
        required: true
        type: boolean
        default: true
      use_bbg:
        required: true
        type: boolean
        default: false
      lxc_enable:
        required: true
        type: boolean
        default: false
      schedhorizon_enable:
        required: true
        type: boolean
        default: false
      only_ak3:
        required: false
        type: boolean
        default: false

jobs:
  build-kernel-a14-6-1-kernelsu-susfs:
    strategy:
      fail-fast: false
      matrix:
        include:
          #- sub_level: "25"
          #  os_patch_level: "2023-10"
          #- sub_level: "43"
          #  os_patch_level: "2023-11"
          #- sub_level: "57"
          #  os_patch_level: "2024-01"
          #- sub_level: "68"
          #  os_patch_level: "2024-03"
          #- sub_level: "75"
          #  os_patch_level: "2024-05"
          - sub_level: "78"
            os_patch_level: "2024-06"
          #- sub_level: "84"
          #  os_patch_level: "2024-07"
          - sub_level: "90"
            os_patch_level: "2024-08"
          #- sub_level: "93"
          #  os_patch_level: "2024-09"
          - sub_level: "99"
            os_patch_level: "2024-10"
          #- sub_level: "112"
          #  os_patch_level: "2024-11"
          #- sub_level: "115"
          #  os_patch_level: "2024-12"
          #- sub_level: "118"
          #  os_patch_level: "2025-01"
          - sub_level: "124"
            os_patch_level: "2025-02"
          #- sub_level: "128"
          #  os_patch_level: "2025-03"
          #- sub_level: "129"
          #  os_patch_level: "2025-04"
          #- sub_level: "134"
          #  os_patch_level: "2025-05"
          - sub_level: "145"
            os_patch_level: "2025-09"
          #- sub_level: "X"
          #  os_patch_level: "lts"
    uses: ./.github/workflows/gki-build.yml
    secrets: inherit
    with:
      android_version: "android14"
      kernel_version: "6.1"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      revision: ${{ matrix.revision }}
      use_zram: ${{ inputs.use_zram }}
      use_kpm: ${{ inputs.use_kpm }}
      use_bbg: ${{ inputs.use_bbg || false }}
      only_ak3: ${{ inputs.only_ak3 || false }}
      lxc_enable: ${{ inputs.lxc_enable || false }}
      schedhorizon_enable: ${{ inputs.schedhorizon_enable || false }}
