name: Android 14 5.15
permissions:
  contents: write
  actions: write

on:
  workflow_call:
    inputs:
      use_zram:
        required: true
        type: boolean
        default: true
      use_kpm:
        required: true
        type: boolean
        default: true
      use_bbg:
        required: true
        type: boolean
        default: false
      only_ak3:
        required: false
        type: boolean
        default: false

jobs:
  build-kernel-a14-5-15-kernelsu-susfs:
    strategy:
      fail-fast: false
      matrix:
        include:
          #- sub_level: "131"
          #  os_patch_level: "2023-11"
          #- sub_level: "137"
          #  os_patch_level: "2024-01"
          #- sub_level: "144"
          #  os_patch_level: "2024-03"
          #- sub_level: "148"
          #  os_patch_level: "2024-05"
          #- sub_level: "153"
          #  os_patch_level: "2024-07"
          #- sub_level: "158"
          #  os_patch_level: "2024-08"
          #- sub_level: "167"
          #  os_patch_level: "2024-11"
          #- sub_level: "170"
          #  os_patch_level: "2025-01"
          #- sub_level: "178"
          #  os_patch_level: "2025-03"
          #- sub_level: "180"
          #  os_patch_level: "2025-05"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/gki-build.yml
    secrets: inherit
    with:
      android_version: "android14"
      kernel_version: "5.15"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      revision: ${{ matrix.revision }}
      use_zram: ${{ inputs.use_zram }}
      use_kpm: ${{ inputs.use_kpm }}
      use_bbg: ${{ inputs.use_bbg || false }}
      only_ak3: ${{ inputs.only_ak3 || false }}
